### ISSUE TITLE
No such file or directory: ‘README.md’

### ISSUE THREAD

**Issue by kseistrup** [iambibhas/gitinit#1]
This happens with python 2.7.3 on linux 3.2.0:

``` pytb
$ sudo pip install gitinit
Downloading/unpacking gitinit
  Running setup.py egg_info for package gitinit
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build/gitinit/setup.py", line 19, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-build/gitinit/setup.py", line 6, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build/gitinit/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build/gitinit/setup.py", line 19, in <module>

    long_description=read('README.md'),

  File "/tmp/pip-build/gitinit/setup.py", line 6, in read

    return open(os.path.join(os.path.dirname(__file__), fname)).read()

IOError: [Errno 2] No such file or directory: '/tmp/pip-build/gitinit/README.md'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build/gitinit
```

**Comment by iambibhas** [comment]
There was a bug with Manifest and README file wasn't being included. I think I've fixed it. Try now.

**Comment by kseistrup** [comment]
I have the same issue with 1.0.4.

``` sh
$ cd /tmp/pip-build/gitinit
$ ls -l
total 16
drwxr-xr-x 3 root root  100 Feb 24 09:06 gitinit
drwxr-xr-x 2 root root  140 Feb 24 09:06 gitinit.egg-info
-rw-r--r-- 1 root root   91 Feb 24 09:06 MANIFEST.in
drwxr-xr-x 2 root root   40 Feb 24 09:06 pip-egg-info
-rw-r--r-- 1 root root 1194 Feb 24 09:06 PKG-INFO
-rw-r--r-- 1 root root   59 Feb 24 09:06 setup.cfg
-rw-r--r-- 1 root root  999 Feb 24 09:06 setup.py
```

No README.md…

**Comment by iambibhas** [comment]
Is it still failing? I checked my xubuntu system -

```
Downloading/unpacking gitinit
  Downloading gitinit-1.0.4.tar.gz
  Running setup.py egg_info for package gitinit

Installing collected packages: gitinit
  Running setup.py install for gitinit

    Installing gitinit script to /usr/local/bin
Successfully installed gitinit
Cleaning up...
```

**Comment by kseistrup** [comment]
Oh, I'm sorry — it seems pip noticed the previous /tmp/pip-build/gitinit directory and didn't bother unpacking 1.0.4 on top of that.  After I removed the build directory gitinit installed flawlessly.  :)

**Comment by iambibhas** [comment]
Ah. Great. This is my first package. So things are a bit shaky. :)
