### ISSUE TITLE
publish latest version 1.0.8 on PyPi

### ISSUE THREAD

**Issue by ChillarAnand** [iambibhas/gitinit#3]
PyPi has 1.0.7 & with Py3, It is throwing error 

```
Traceback (most recent call last):
  File "/home/k3/.virtualenvs/py3/bin/gitinit", line 9, in <module>
    load_entry_point('gitinit==1.0.7', 'console_scripts', 'gitinit')()
  File "/home/k3/.virtualenvs/py3/lib/python3.4/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/k3/.virtualenvs/py3/lib/python3.4/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/home/k3/.virtualenvs/py3/lib/python3.4/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
  File "/home/k3/.virtualenvs/py3/lib/python3.4/site-packages/gitinit/gitinit.py", line 45
    print 'Creating .gitignore ...'
                                  ^
SyntaxError: invalid syntax
```

**Comment by iambibhas** [comment]
Just pushed, trying upgrading - 

```
$ sudo pip install --upgrade gitinit
```

**Comment by ChillarAnand** [comment]
Thank You  :cake:
